spring:
  application:
    name: gateway

server:
  port: 8080

gateway:
  upstream:
    auth: http://localhost:8082/auth/api
    customer: http://localhost:8086/customer/api
    core-data: http://localhost:8081/core-data/api
  cors:
    allowed-origin-patterns:
      - "http://localhost:*"
      - "http://127.0.0.1:*"
